namespace BaseCustomFactions.SoundReplacement.FactionVoiceLineSounds
{
    public enum VoiceLineTypes
    {
        Cheer,
        Compliment,
        ChallengeToDuel,
        TakeCover,
        GoodShot,
        Help,
        Insult,
        Surgeon,
        ProclaimMutiny,
        No,
        PatrioticCheer,
        Retreat,
        Salute,
        StandGround,
        StayCalm,
        Surrender,
        Taunt,
        Thanks,
        WarCry,
        Yes,
        MakeReady,
        FireAtWill,
        CeaseFire,
        Charge,
        Fire
    }
}